accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.Register.as_view(), name="register"),
    path("profile/", views.Profile.as_view(), name="profile")
]

blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
]

djcms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("accounts/", include("accounts.urls")),
    path("blogs/", include("blogs.urls")),
    path("manage/", include("management.urls")),

    path("", views.Index.as_view(), name="index"),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("latest/", views.Latest.as_view(), name="latest"),
    path("popular/", views.Popular.as_view(), name="popular"),
    path("search/", views.Search.as_view(), name="search"),
    path("bookmark/", views.BookmarkView.as_view(), name="bookmark"),
    path("terms-and-conditions/", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("category/", views.CategoryView.as_view(), name="category"),
    path("category/<slug:cat>/", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(default="", max_length=30)
    desc = models.TextField()
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.category
    
class Blog(models.Model):
    slug = models.SlugField(unique=True, null=False, blank=False, max_length=100)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    content = RichTextField()
    thumbnail = models.ImageField(upload_to="thumbnails/%Y/%m/%d/")
    views = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name="blogs")
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=True)
    published_on = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="blogs", null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

class Comment(models.Model):
    comment = models.TextField()
    likes = models.IntegerField(default=0)
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="comments", null=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="comments", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.comment

class Reply(models.Model):
    reply = models.TextField()
    likes = models.IntegerField(default=0)
    comment = models.ForeignKey(to=Comment, on_delete=models.SET_NULL, related_name="replies", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="replies", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.reply

class Bookmark(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Bookmark({self.id}, {self.creater.username})"

class BlogLike(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)

    def __str__(self):
        return f"BlogLike({self.id}, {self.creator.username})"

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.db.models import F
from django.urls import reverse
from .models import *

# Create your views here.
def get_blog_url(slug):
    return reverse("blogs:blog", args=[slug])

class BlogView(View):
    def get(self, request, slug):
        queryset = Blog.objects.filter(is_active=True, slug=slug)
        blog = get_object_or_404(queryset)
        blog.views = F("views") + 1
        blog.save()
        blog.refresh_from_db()

        context = {
            "blog": blog,
            "comments": blog.comments.filter(is_active=True)
        }
        if request.user.is_authenticated:
            context["bookmarked"] = Bookmark.objects.filter(creator=request.user, blog=blog).first()
            context["liked"] = BlogLike.objects.filter(blog=blog, creator=request.user).first()

        return render(request, "blogs/blog.html", context)

class CreateComment(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        comment = request.POST.get("comment")
        if not comment:
            messages.warning(request, "Comment required")
            return redirect("blogs:blog", slug=blog.slug)
        c = Comment(
            comment = comment,
            creator = request.user,
            blog = blog
        )
        c.save()
        messages.success(request, "Comment created")
        return redirect(get_blog_url(blog.slug)+"#comments")

class CreateReply(View):
    def post(self, request):
        comment = get_object_or_404(Comment.objects.filter(is_active=True, id=request.POST.get("id")))
        reply = request.POST.get("reply")
        if not reply:
            messages.warning(request, "Reply required")
            return redirect("blogs:blog", slug=comment.blog.slug)

        r = Reply(
            reply = request.POST.get("reply", ""),
            comment = comment,
            creator = request.user
        )
        r.save()

        messages.success(request, "Reply created")
        return redirect(get_blog_url(comment.blog.slug)+"#comments")

class CreateBookmark(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        bookmarked = Bookmark.objects.filter(creator=request.user, blog=blog).first()
        if bookmarked:
            messages.info(request, "Already bookmarked this blog")
        else:
            b = Bookmark(
                blog = blog,
                creator = request.user
            )
            b.save()
            messages.success(request, "Bookmark created")
        return redirect("blogs:blog", slug=blog.slug)

class CreateLike(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        liked = BlogLike.objects.filter(blog=blog, creator=request.user).first()
        if liked:
            messages.info(request, "You are already liked this post")
        else:
            l = BlogLike(creator=request.user, blog=blog)
            l.save()
            messages.success(request, "Liked this blog")
        return redirect(get_blog_url(blog.slug)+"#features")

blogs/templates/blogs/blog.html
{% extends 'layout.html' %}

{% block ogtitle %}{{ blog.title }}{% endblock %}
{% block ogdescription %}{{ blog.desc }}{% endblock %}
{% block ogimage %}{{ blog.thumbnail.url }}{% endblock %}

{% block title %}Blog{% endblock %}

{% block body %}
{% load static %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h2>
      {{ blog.title }}
    </h2>
  </div>
  <div class="row">
    <p>Author: {{ blog.creator }} | Views: {{ blog.views }} | Updated: {{ blog.published_on|timesince }} ago</p>
  </div>
  <div class="row mb-3">
    {% for category in blog.categories.all %}
      {% if category.is_active %}
      <div class="col">
        <a type="button" href="{% url 'get_category' category.slug %}" class="btn btn-primary btn-sm ms-auto">{{ category.category }}</a>
      </div>
      {% endif %}
    {% endfor %}
  </div>
  <div class="row">
    <div class="ratio ratio-16x9">
      <img src="{{ blog.thumbnail.url }}" class="img-fluid rounded mx-auto d-block" alt="blog's thumbnail">
    </div>
    <p>
      {{ blog.content|safe }}
    </p>
  </div>
  <br>
  <div class="row" id="features">
    <div class="col">
      {% if liked %}
      <a href="#" class="text-decoration-none">
        <i class="bi bi-hand-thumbs-up-fill"></i>
        {{ blog.likes.count }}
      </a>
      {% else %}
      <form action="{% url 'blogs:create_like' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{blog.id}}">
        <button type="submit" style="background:none!important;border:none;padding:0!important;" class="text-primary">
          <i class="bi bi-hand-thumbs-up"></i>
          {{ blog.likes.count }}
        </button>
      </form>
      {% endif %}
    </div>
    <div class="col">
      <a href="#comments" class="text-decoration-none">
        <i class="bi bi-chat-text"></i>
        {{ comments.count }}
      </a>
    </div>
    <div class="col">
      {% if bookmarked %}
      <a href="#" class="text-decoration-none float-end">
        <i class="bi bi-bookmark-check-fill"></i>
      </a>
      {% else %}
      <form action="{% url 'blogs:create_bookmark' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{blog.id}}">
        <button type="submit" style="background:none!important;border:none;padding:0!important;" class="float-end text-primary">
          <i class="bi bi-bookmark-plus"></i>
        </button>
      </form>
      {% endif %}
    </div>
    <div class="col">
      <button class="text-primary float-end" style="background:none!important;border:none;padding:0!important;" data-bs-toggle="modal" data-bs-target="#shareModal">
        <i class="bi bi-box-arrow-up"></i>
      </button>
    </div>
  </div>
  <br><br><hr>
  
  <div class="row mb-3" id="comments">
    <h1>
      <i class="bi bi-chat-left-text"></i>
      Comments ({{ comments.count }})
    </h1>
  </div>
  <div class="row">
    <form action="{% url 'blogs:create_comment' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{ blog.id }}">
      <div class="mb-3">
        <label for="comment" class="form-label">Comment:</label>
        <textarea class="form-control" id="comment" rows="3" name="comment" placeholder="Add a comment" required></textarea>
      </div>
      {% if request.user.is_authenticated %}
      <button type="submit" class="float-end btn btn-primary">
        <i class="bi bi-send"></i>
        Submit
      </button>
      {% else %}
      <a href="{% url 'accounts:login' %}" class="btn btn-primary float-end">Login</a>
      {% endif %}
    </form>
  </div>
  <br>
  <br><hr><br>
  {% for comment in comments %}
  <div class="row">
    <b>@{{ comment.creator.username }}<b>
    <span class="badge text-bg-primary">{{ comment.published_on }}</span>
    <p>{{ comment.comment }}</p>
    <a class="text-decoration-none" data-bs-toggle="collapse" href="#reply{{comment.id}}" role="button" aria-expanded="false" aria-controls="reply{{comment.id}}">
      <i class="bi bi-reply"></i>
      Reply
    </a>
    <div class="collapse" id="reply{{comment.id}}">
      <div class="card card-body">
        {% for reply in comment.replies.all %}
        <b>@{{ reply.creator.username }}<b>
        <span class="badge text-bg-primary">{{ reply.published_on }}</span>
        <p>{{ reply.reply }}</p>
        <hr>
        {% endfor %}
        <form action="{% url 'blogs:create_reply' %}" method="post">
          {% csrf_token %}
          <div class="row"> 
            <input type="hidden" name="id" value="{{comment.id}}">
            <div class="col-10">
              <input type="text" class="form-control" name="reply" placeholder="Add a reply" required>
            </div>
            <div class="col-2">
              <button type="submit" class="btn btn-primary">
                <i class="bi bi-send"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <hr>
  {% endfor %}
</div>

<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Share</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <button class="btn btn-primary">
          <i class="bi bi-facebook"></i>
        </button>
        <button class="btn btn-success">
          <i class="bi bi-whatsapp"></i>
        </button>
        <button class="btn btn-dark">
          <i class="bi bi-twitter-x"></i>
        </button>
        <button class="btn btn-info">
          <i class="bi bi-instagram"></i>
        </button>
        <button class="btn btn-primary">
          <i class="bi bi-telegram"></i>
        </button>
        <button class="btn btn-outline-secondary rounded-pill" id="copyBtn" onclick="copyUrl()">
          <i class="bi bi-copy"></i>
        </button>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/blogs/blog.js' %}"></script>
{% endblock %}