blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
]

djcms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("accounts/", include("accounts.urls")),
    path("blogs/", include("blogs.urls")),
    path("manage/", include("management.urls")),

    path("", views.Index.as_view(), name="index"),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("latest/", views.Latest.as_view(), name="latest"),
    path("popular/", views.Popular.as_view(), name="popular"),
    path("search/", views.Search.as_view(), name="search"),
    path("bookmark/", views.BookmarkView.as_view(), name="bookmark"),
    path("terms-and-conditions/", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("category/", views.CategoryView.as_view(), name="category"),
    path("category/<slug:cat>/", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views

app_name = "manage"

urlpatterns = [
    path("blog/", views.ManageBlog.as_view(), name="blog"),
    path("category/", views.ManageCategory.as_view(), name="category"),
    path("comment/", views.ManageComment.as_view(), name="comment"),

    path("create/blog/", views.CreateBlog.as_view(), name="create_blog"),
    path("create/category/", views.CreateCategory.as_view(), name="create_category"),

    path("delete/blog/<int:id>/", views.DeleteBlog.as_view(), name="delete_blog"),
    path("delete/category/<int:id>", views.DeleteCategory.as_view(), name="delete_category"),
    path("delete/comment/<int:id>", views.DeleteComment.as_view(), name="delete_comment"),

    path("edit/blog/<int:id>/", views.EditBlog.as_view(), name="edit_blog"),
    path("edit/category/<int:id>", views.EditCategory.as_view(), name="edit_category"),
]

blogs/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(default="", max_length=30)
    desc = models.TextField()
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.category
    
class Blog(models.Model):
    slug = models.SlugField(unique=True, null=False, blank=False, max_length=100)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    content = RichTextField()
    thumbnail = models.ImageField(upload_to="thumbnails/%Y/%m/%d/")
    views = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name="blogs")
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=True)
    published_on = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="blogs", null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

class Comment(models.Model):
    comment = models.TextField()
    likes = models.IntegerField(default=0)
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="comments", null=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="comments", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.comment

class Reply(models.Model):
    reply = models.TextField()
    likes = models.IntegerField(default=0)
    comment = models.ForeignKey(to=Comment, on_delete=models.SET_NULL, related_name="replies", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="replies", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.reply

class Bookmark(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Bookmark({self.id}, {self.creater.username})"

class BlogLike(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)

    def __str__(self):
        return f"BlogLike({self.id}, {self.creator.username})"

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

class CKEditorForm(forms.Form):
    content = forms.CharField(widget = CKEditorWidget())

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.db.models import F
from django.urls import reverse
from .models import *

# Create your views here.
def get_blog_url(slug):
    return reverse("blogs:blog", args=[slug])

class BlogView(View):
    def get(self, request, slug):
        queryset = Blog.objects.filter(is_active=True, slug=slug)
        blog = get_object_or_404(queryset)
        blog.views = F("views") + 1
        blog.save()
        blog.refresh_from_db()

        context = {
            "blog": blog,
            "comments": blog.comments.filter(is_active=True)
        }
        if request.user.is_authenticated:
            context["bookmarked"] = Bookmark.objects.filter(creator=request.user, blog=blog).first()
            context["liked"] = BlogLike.objects.filter(blog=blog, creator=request.user).first()

        return render(request, "blogs/blog.html", context)

class CreateComment(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        comment = request.POST.get("comment")
        if not comment:
            messages.warning(request, "Comment required")
            return redirect("blogs:blog", slug=blog.slug)
        c = Comment(
            comment = comment,
            creator = request.user,
            blog = blog
        )
        c.save()
        messages.success(request, "Comment created")
        return redirect(get_blog_url(blog.slug)+"#comments")

class CreateReply(View):
    def post(self, request):
        comment = get_object_or_404(Comment.objects.filter(is_active=True, id=request.POST.get("id")))
        reply = request.POST.get("reply")
        if not reply:
            messages.warning(request, "Reply required")
            return redirect("blogs:blog", slug=comment.blog.slug)

        r = Reply(
            reply = request.POST.get("reply", ""),
            comment = comment,
            creator = request.user
        )
        r.save()

        messages.success(request, "Reply created")
        return redirect(get_blog_url(comment.blog.slug)+"#comments")

class CreateBookmark(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        bookmarked = Bookmark.objects.filter(creator=request.user, blog=blog).first()
        if bookmarked:
            messages.info(request, "Already bookmarked this blog")
        else:
            b = Bookmark(
                blog = blog,
                creator = request.user
            )
            b.save()
            messages.success(request, "Bookmark created")
        return redirect("blogs:blog", slug=blog.slug)

class CreateLike(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        liked = BlogLike.objects.filter(blog=blog, creator=request.user).first()
        if liked:
            messages.info(request, "You are already liked this post")
        else:
            l = BlogLike(creator=request.user, blog=blog)
            l.save()
            messages.success(request, "Liked this blog")
        return redirect(get_blog_url(blog.slug)+"#features")

management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from blogs.models import Category, Blog, Comment
from django.utils import timezone
from .forms import CKEditorForm

# Create your views here.
class ManageBlog(View):
    def get(self, request):
        blogs = Blog.objects.filter(is_active=True, creator=request.user)
        return render(request, "management/blog.html", {"blogs": blogs})

class ManageCategory(View):
    def get(self, request):
        categories = Category.objects.filter(is_active=True)
        return render(request, "management/category.html", {"categories": categories})


class CreateBlog(View):
    def get(self, request):
        form = CKEditorForm()
        categories = Category.objects.filter(is_active=True)
        return render(request, "management/create_blog.html", {"form": form, "categories": categories})

    def post(self, request):
        data = request.POST
        title = data.get("title")
        desc = data.get("desc")
        content = data.get("content")
        thumbnail = request.FILES.get("thumbnail")
        categories = data.getlist("categories") 
        status = data.get("status")

        if not (title and desc and content and thumbnail and categories and status):
            messages.info(request, "title, desc, content, thumbnail, categories, or status can't be empty")
            return redirect("manage:create_blog")

        try:
            status = bool(int(status))
        except:
            messages.info(request, "Something wrong with status")
            return redirect("manage:create_blog")

        blog = Blog(
            title = title,
            desc = desc,
            content = content,
            creator = request.user,
            thumbnail = thumbnail,
            is_published = status
        )
        blog.save()
        for id in categories:
            try:
                c = Category.objects.get(id=int(id))
                blog.categories.add(c)
            except Exception as e:
                pass

        blog.save()
        messages.success(request, "Blog created")

        return redirect("manage:create_blog")


class CreateCategory(View):
    def get(self, request):
        return render(request, "management/create_category.html")

    def post(self, request):
        data = request.POST
        category = data.get("category")
        desc = data.get("desc")

        c = Category.objects.filter(category=category).first()
        if c is not None:
            messages.warning(request, "Category already exists")
        else:
            c = Category(
                category=category,
                desc=desc
            )
            c.save()
            messages.success(request, "Category created")
        return redirect("manage:create_category")
        
class EditBlog(View):
    def get(self, request, id):
        blog = Blog.objects.filter(id=id, creator=request.user).first()
        if blog is None:
            messages.info(request, "Blog not exists")
            return redirect("manage:blog")
        categories = Category.objects.all()
        form = CKEditorForm({"content": blog.content})
        return render(request, "management/edit_blog.html", {"blog": blog, "categories": categories, "form": form})
    
    def post(self, request, id = None):
        data = request.POST
        id = data.get("id")
        blog = Blog.objects.filter(is_active=True, creator=request.user, id=id).first()
        if blog is None:
            messages.info(request, "Blog doesn't exists")
            return redirect("manage:blog")

        title = data.get("title")
        desc = data.get("desc")
        content = data.get("content")
        status = data.get("status")
        thumbnail = request.FILES.get("thumbnail")
        categories = data.getlist("categories")

        blog.title = title
        blog.desc = desc
        blog.content = content
        if thumbnail:
            blog.thumbnail = thumbnail

        try:
            status = int(status)
            if not blog.is_published and status:
                blog.published_on = timezone.now()
            blog.is_published = bool(status)
        except:
            messages.info(request, "Error while updating status")
        
        blog.categories.set([])
        for id in categories:
            try:
                c = Category.objects.get(id=int(id))
                blog.categories.add(c)
            except Exception as e:
                pass

        blog.save()
        messages.success(request, "Changes saved")

        return redirect("manage:blog")

class DeleteBlog(View):
    def get(self, request, id):
        blog = Blog.objects.filter(id=id, creator=request.user).first()
        if blog is None:
            messages.warning(request, "Blog doesn't exists")
        else:
            blog.is_active = False
            blog.save()
            messages.info(request, "Blog deleted")

        return redirect("manage:blog")

class EditCategory(View):
    def get(self, request, id):
        category = get_object_or_404(Category, id=id, is_active=True)
        return render(request, "management/edit_category.html", {"category": category})

    def post(self, request, id):
        c = Category.objects.filter(id=id, is_active=True).first()
        data = request.POST
        category, desc = data.get("category"), data.get("desc")
        if not ((category and desc) or c):
            messages.warning(request, "Category or Desc can't be empty. OR Category doesn't exists")
            return redirect("manage:category")
        c.category = category
        c.desc = desc
        c.save()
        messages.success(request, "Changes saved")
        return redirect("manage:category")
        

class DeleteCategory(View):
    def get(self, request, id):
        category = get_object_or_404(Category, id=id)
        category.is_active = False
        category.save()
        messages.info(request, "Category removed")
        return redirect("manage:category")

class ManageComment(View):
    def get(self, request):
        comments = Comment.objects.filter(is_active=True, blog__in=Blog.objects.filter(creator=request.user))
        return render(request, "management/comment.html", {"comments": comments})

class DeleteComment(View):
    def get(self, request, id):
        comment = get_object_or_404(Comment.objects.filter(id=id, is_active=True))
        if comment.blog.creator.username != request.user.username:
            messages.warning(request, "You are not author of that blog")
            return redirect("manage:comment")
        comment.is_active = False
        comment.save()
        messages.success(request, "Comment deleted")
        return redirect("manage:comment")

management/templates/management/blog.html
{% extends 'layout.html' %}

{% block title %}Manage{% endblock %}

{% block body %}
<div class="container table-responsive">
  <div class="row mb-3">
    <h1 class="text-center mb-3 mt-3">
      Manage Blogs
    </h1>
  </div>
  <div class="mb-3 text-end">
    <a role="button" class="btn btn-primary fw-semibold px-3 py-2" href='{% url 'manage:create_blog' %}' style="border-radius: 6px; transition: 0.3s;">
      <i class="bi bi-plus-lg"></i>
      Create Blog
    </a>
  </div>
  <div class="row">
    {% include 'management/blog_table.html' with blogs=blogs %}
  </div>
</div>
{% endblock %}

management/templates/management/blog_table.html
<table class="table table-hover" style="border-collapse: collapse; width: 100%; background: #fff; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1); border-radius: 8px; overflow: hidden;">
  <thead>
    <tr style="background: linear-gradient(to right, #007bff, #0056b3); color: white; font-weight: 600; text-align: center;">
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">#</th>
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">ID</th>
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Title</th>
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Desc</th>
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Categories</th>
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Created On</th>
      <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Is Published</th>
      <th scope="col" style="padding: 12px;">Actions</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    {% for blog in blogs %}
    <tr style="text-align: center; border-bottom: 1px solid #ddd;">
      <th scope="row" style="padding: 12px; font-weight: 600;">{{ forloop.counter }}</th>
      <td style="padding: 12px; color: #555;">{{ blog.id }}</td>
      <td style="padding: 12px; font-weight: 500;">{{ blog.title|truncatechars:30 }}</td>
      <td style="padding: 12px; color: #666;">{{ blog.desc|truncatechars:50 }}</td>
      <td style="padding: 12px; color: #007bff; font-weight: 500;">[{{ blog.categories.all|join:", " }}]</td>
      <td style="padding: 12px; color: #555;">{{ blog.published_on }}</td>
      <td style="padding: 12px; font-weight: 600; color: {% if blog.is_published %}#28a745{% else %}#dc3545{% endif %};">
        {% if blog.is_published %}Yes{% else %}No{% endif %}
      </td>
      <td style="padding: 12px;">
        <a class="btn" href="{% url 'manage:edit_blog' blog.id %}" role="button"
           style="background: #ffc107; color: #222; padding: 6px 12px; font-size: 14px; border-radius: 5px; font-weight: 600; transition: 0.3s;">
          <i class="bi bi-pencil-square"></i> Edit
        </a>
        <a class="btn" href="{% url 'manage:delete_blog' blog.id %}" role="button"
           style="background: #dc3545; color: white; padding: 6px 12px; font-size: 14px; border-radius: 5px; font-weight: 600; transition: 0.3s;">
          <i class="bi bi-trash3"></i> Delete
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

management/templates/management/category.html
{% extends 'layout.html' %}

{% block title %}Category{% endblock %}

{% block body %}
<div class="container mt-5">
  
  <!-- Page Title -->
  <div class="row mb-4">
    <h1 class="text-center fw-bold" style="color: #fff;">Manage Categories</h1>
  </div>

  <!-- Create Category Button -->
  <div class="mb-3 text-end">
    <a role="button" class="btn btn-primary fw-semibold px-3 py-2" href='{% url "manage:create_category" %}' 
       style="border-radius: 6px; transition: 0.3s;">
      <i class="bi bi-plus-lg"></i> Create Category
    </a>
  </div>

  <!-- Categories Table -->
  <div class="row">
    <table class="table table-hover" 
           style="border-collapse: collapse; width: 100%; background: #fff; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1); border-radius: 8px; overflow: hidden;">
      <thead>
        <tr style="background: linear-gradient(to right, #007bff, #0056b3); color: white; font-weight: 600; text-align: center;">
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">#</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">ID</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Category</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Desc</th>
          <th scope="col" style="padding: 12px;">Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for category in categories %}
        <tr style="text-align: center; border-bottom: 1px solid #ddd;">
          <th scope="row" style="padding: 12px; font-weight: 600;">{{ forloop.counter }}</th>
          <td style="padding: 12px; color: #555;">{{ category.id }}</td>
          <td style="padding: 12px; font-weight: 500;">{{ category.category|truncatechars:30 }}</td>
          <td style="padding: 12px; color: #666;">{{ category.desc|truncatechars:50 }}</td>
          <td style="padding: 12px;">
            <a class="btn" href="{% url 'manage:edit_category' category.id %}" role="button"
               style="background: #ffc107; color: #222; padding: 6px 12px; font-size: 14px; border-radius: 5px; font-weight: 600; transition: 0.3s;">
              <i class="bi bi-pencil-square"></i> Edit
            </a>
            <a class="btn" href="{% url 'manage:delete_category' category.id %}" role="button"
               style="background: #dc3545; color: white; padding: 6px 12px; font-size: 14px; border-radius: 5px; font-weight: 600; transition: 0.3s;">
              <i class="bi bi-trash3"></i> Delete
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

management/templates/management/comment.html
{% extends 'layout.html' %}

{% block title %}Manage Comments{% endblock %}

{% block body %}
<div class="container mt-5">

  <!-- Page Title -->
  <div class="row mb-4">
    <h1 class="text-center fw-bold" style="color: #fff;">Manage Comments</h1>
  </div>

  <!-- Comments Table -->
  <div class="row">
    <table class="table table-hover" 
           style="border-collapse: collapse; width: 100%; background: #fff; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1); border-radius: 8px; overflow: hidden;">
      <thead>
        <tr style="background: linear-gradient(to right, #007bff, #0056b3); color: white; font-weight: 600; text-align: center;">
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">#</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">ID</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Comment</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Creator</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Blog ID</th>
          <th scope="col" style="padding: 12px; border-right: 1px solid #ddd;">Blog Title</th>
          <th scope="col" style="padding: 12px;">Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for comment in comments %}
        <tr style="text-align: center; border-bottom: 1px solid #ddd;">
          <th scope="row" style="padding: 12px; font-weight: 600;">{{ forloop.counter }}</th>
          <td style="padding: 12px; color: #555;">{{ comment.id }}</td>
          <td style="padding: 12px; font-weight: 500;">{{ comment.comment|truncatechars:30 }}</td>
          <td style="padding: 12px; color: #666;">{{ comment.creator.username }}</td>
          <td style="padding: 12px; font-weight: 500;">{{ comment.blog.id }}</td>
          <td style="padding: 12px; color: #555;">{{ comment.blog.title|truncatechars:30 }}</td>
          <td style="padding: 12px;">
            <a class="btn" href="{% url 'manage:delete_comment' comment.id %}" role="button"
               style="background: #dc3545; color: white; padding: 6px 12px; font-size: 14px; border-radius: 5px; font-weight: 600; transition: 0.3s;">
              <i class="bi bi-trash3"></i> Delete
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
{% endblock %}

management/templates/management/create_category.html
{% extends 'layout.html' %}

{% block title %}Add Category{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <form method="post" action="{% url 'manage:create_category' %}">
    {% csrf_token %}
    <h1 class="text-center mb-3">
      Add Category
    </h1>
    <div class="mb-3">
      <label for="category" class="form-label">Category:</label>
      <input type="text" class="form-control" id="category" placeholder="category" name="category">
    </div>
    <div class="mb-3">
      <label for="desc" class="form-label">Description:</label>
      <textarea class="form-control" id="desc" rows="5" name="desc" placeholder="Type description here"></textarea>
    </div>
    <div class="row float-end">
      <button type="submit" class="btn btn-outline-success">Create</button>
    </div>
  </form>
</div>
{% endblock %}

management/templates/management/edit_blog.html
{% extends 'layout.html' %}

{% block title %}Edit Blog{% endblock %}

{% block body %}
<div class="container mt-5 mb-5" style="max-width: 1000px; background: #fff; padding: 25px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1); border-radius: 8px;">
  <form method="post" action="{% url 'manage:edit_blog' blog.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ blog.id }}">

    <h1 class="text-center mb-4" style="color: #333; font-weight: 600;">Edit Blog</h1>

    <!-- Blog Title -->
    <div class="mb-3">
      <label for="title" class="form-label fw-bold" style="color: #000;">Title:</label>
      <input type="text" class="form-control" id="title" placeholder="Enter blog title" name="title" value="{{ blog.title }}" required style="border-radius: 5px;">
    </div>

    <!-- Blog Description -->
    <div class="mb-3">
      <label for="desc" class="form-label fw-bold" style="color: #000;">Description:</label>
      <textarea class="form-control" id="desc" placeholder="Write a short description..." style="height: 120px; border-radius: 5px;" name="desc">{{ blog.desc }}</textarea>
    </div>

    <!-- Text Editor (Django Form Media) -->
    <div class="mb-3">
      <label class="form-label fw-bold" style="color: #000;">Content:</label>
      <div style="border: 1px solid #ddd; padding: 10px; border-radius: 5px; background: #f9f9f9;">
        {{ form.media }}
        {{ form.as_p }}
      </div>
    </div>

    <!-- Thumbnail Upload -->
    <div class="mb-3">
      <label for="thumbnail" class="form-label fw-bold" style="color: #000;">Thumbnail:</label>
      <input class="form-control" type="file" id="thumbnail" name="thumbnail" accept="image/*" style="border-radius: 5px;">
      {% if blog.thumbnail %}
        <small class="d-block mt-1" style="color: #000;">Current: <a class="text-decoration-none" href="{{ blog.thumbnail.url }}" target="_blank" style="color: #007bff;">View Current Thumbnail</a></small>
      {% endif %}
    </div>

    <!-- Category Selection -->
    <div class="mb-3">
      <label for="categories" class="form-label fw-bold" style="color: #000;">Categories:</label>
      <select id="categories" class="form-select" multiple name="categories" required style="border-radius: 5px;">
        <option disabled value="">Select categories</option>
        {% for category in categories %}
        <option value="{{ category.id }}" {% if category in blog.categories.all %}selected{% endif %}>{{ category.category }}</option>
        {% endfor %}
      </select>
      <small class="d-block mt-1" style="color: #000;">Don't see a category? <a class="text-decoration-none" href="{% url 'manage:create_category' %}" style="color: #007bff;">Create one</a></small>
    </div>

    <!-- Blog Status -->
    <div class="mb-3">
      <label class="form-label fw-bold" style="color: #000;">Status:</label>
      <div class="d-flex align-items-center gap-3">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="status" value="0" id="draft" {% if not blog.is_published %}checked{% endif %}>
          <label class="form-check-label" for="draft" style="color: #000;">Draft</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="status" value="1" id="publish" {% if blog.is_published %}checked{% endif %}>
          <label class="form-check-label" for="publish" style="color: #000;">Publish</label>
        </div>
      </div>
    </div>

    <!-- Submit Button -->
    <div class="text-end">
      <button type="submit" class="btn btn-success px-4 py-2 fw-bold" style="border-radius: 5px;">Update</button>
    </div>

  </form>
</div>
{% endblock %}

management/templates/management/edit_category.html
{% extends 'layout.html' %}

{% block title %}Edit Category{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mb-3">
      Edit Category
    </h1>
  </div>
  <div class="row">
    <form method="post" action="{% url 'manage:edit_category' category.id %}">
      {% csrf_token %}
      <div class="row mb-3">
        <label for="category" class="form-label">Category:</label>
        <input type="text" class="form-control" id="category" placeholder="Category" name="category" value="{{ category.category }}" required autofocus>
      </div>
      <div class="row mb-3">
        <label for="desc" class="form-label">Description:</label>
        <textarea class="form-control" placeholder="Type description here" id="desc" style="height: 100px" name="desc">{{ category.desc }}</textarea>
      </div>
      <div class="row float-end">
        <button type="submit" class="btn btn-outline-success">Save</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}